PixelgenTechnologies/pixelatorR

R/graph_layout.R

One little dot to fix the mean calculation in layout normalization to apply the mean per coordinate axis.

fix: fixed layout normalization mean

---

.Rbuildignore
.gitignore
R/load_cell_graphs.R
tests/testthat/test-LoadCellGraphs.R

This fixes a bug where LoadCellGraphs would mix up the names of components when `object` contains multiple samples, thus returning an `object` where `CellGraphs` would get the data of other components. 
There was also a new test created to check for bugs of this type, but it is currently not functional since the current test data has some discrepancies between the edgelist and the count matrices. Let's discuss if that test should be brought in here.

fix: fixed accidental layout mix up

---

DESCRIPTION

A new version of [arrow](https://cran.r-project.org/web/packages/arrow/index.html) (R package, v15.0.1) was recently released on CRAN which appears to break the tests in pixelatorR. 
Several bugs have already been reported on the arrow GH repo: 
https://github.com/apache/arrow/issues/40624,
https://github.com/apache/arrow/issues/40627, 
https://github.com/apache/arrow/issues/40593
Since the version is already is released on CRAN, this is the version people will get if they install the package with `install.packages("arrow")`. I tried pinning the version in the DESCRIPTION file by setting `arrow (<= 14.0.2.1)`, but on our GH action R CMD check, it couldn't find the version. 
As a fix, I included the following field in the DESCRIPTION file:
````
Remotes:
cran/arrow@14.0.2.1
````
This should …

Pinned arrow version to 14.0.2.1

---

CHANGELOG.md
R/edge_rank_plot.R

This fixes a bug in `EdgeRankPlot` induced by the renaming of the column "edges" to "molecules" in the `CellGraphAssay` meta.data slot.
Fixes: exe-1620
Function has been manually tested with input will both version of the column name.

fix: EdgeRankPlot now accepts molecules or edges

---

R/load_data.R

`pixelatorR::ReadMPX_Seurat()` creates the following duplicated metadata variables when reading PXL files:
- nFeature_mpxCells (duplicate of antibodies)
- nCount_mpxCells(duplicate of edges)
Fixes: exe-1537

Removed redundant meta data columns

---

R/graph_layout.R
inst/WORDLIST
man/ComputeLayout.Rd
tests/testthat/test-ComputeLayout.R

Would be good to be able to have multiple pmds layouts in the same SeuratObject for example. E.g. if you'd want one regular and one normalized pmds layout.
`ComputeLayout` now takes a new argument `layout_name` which, if provided, will determine the name of the saved layout. The argument `custom_layout_name` has been deprecated in favor of `layout_name`. If a custom layout function is provided and no `layout_name` is provided, `layout_name` will default to "custom".
Fixes: exe-1462
Updated test for ComputeLayout.

Added fix to exe-1462

---

CHANGELOG.md
DESCRIPTION
R/load_cell_graphs.R

Edgelists produced with the current dev version of Pixelator writes the upia/upib columns as dictionaries in the parquet file which causes issues in `LoadCellGraphs`. In R, these dictionaries are loaded as factors. This PR provides a fix by converting the upia/upib columns to character vectors.
Fixes: exe-1721

Updated LoadCellGraphs

---

CHANGELOG.md
DESCRIPTION
R/local_G.R
README.md
man/compute_transition_probabilities.Rd
man/local_G.Rd
tests/testthat/test-JoinLayers.R
tests/testthat/test-local_G.R

By default, a weighting scheme based on transition probabilities is used to compute local G. When setting `use_weights=FALSE`, the adjacency matrix is used for computations where edge weights are equal to 1. The `k` parameter adjusts the size of the node neighborhoods by computing matrix powers, but this is currently ignored when `use_weights=FALSE`. In other words, we want to make sure that the neighborhoods are expanded properly when `k>1` and `use_weights=FALSE`.
This PR provides a fix for the abovementioned issue.
Fixes: exe-1792
Added test to ensure that `local_G` returns different results when: (1) `k=1` and `use_weights=FALSE`, (2) `k>1` and `use_weights=FALSE`.

Fixed bug in local_G

---

CHANGELOG.md
DESCRIPTION
R/load_data.R
README.md
tests/testthat/test-ReadMPX_Seurat.R

This is a fix of a bug where `load_polarity_scores` is used instead of `load_colocalization_scores` to control whether to read colocalization scores in ReadMPX_Seurat:
Fixes: EXE-1836
New tests have been added to check for correct behavior.

fix: loading colocalization bug in ReadMPX_Seurat

---

CHANGELOG.md
DESCRIPTION
R/local_G.R
README.md
man/local_G.Rd

The equations for local Gi and G*i are in the wrong order due to an error made in the literature the equation was taken from. I have looked at the original article and other articles written by Getis and Ord who developed the statistic to confirm this.
This PR adds an update to the function documentation of local G that reflects the original definitions.
Fixes: exe-1856

fix: local G documentation

---

CHANGELOG.md
R/tau_plot.R
tests/testthat/test-TauPlot.R

Due to the name changes in summary metrics created by Pixelator (stored in `adata.obs`), the `TauPlot` function fails.
````
> TauPlot(se)
Error in `TauPlot()`:
! 'umi_per_upia' and 'tau' must be available from the meta.data slot
Run `rlang::last_trace()` to see where the error occurred.
````
This PR adds a fix to handle name change. Since 'umi_per_upia' doesn't have an equivalent column in `obs`, we use the 'mean_molecules_per_a_pixel' column as a replacement. If both columns are present in `obs`, the first one gets picked.
Fixes: exe-1796
Added a test to simulate the name change by replacing the 'mean_umi_per_upia' with 'mean_molecules_per_a_pixel'.

updated TauPlot for compatibility with 0.18 metric names

---

CHANGELOG.md
DESCRIPTION
R/graph_layout.R
R/graph_layout_visualization.R
R/local_G.R
R/weighted_pmds.R
README.md
man/ComputeLayout.Rd
man/Plot3DGraph.Rd
man/layout_with_weighted_pmds.Rd
man/local_G.Rd
tests/testthat/test-ComputeLayout.R
tests/testthat/test-Plot3dGraph.R

In order to match the naming convention for layouts in the pixelator Python implementation, we should add a suffix to the names of 3D layouts.
This PR adds a minor change to `ComputeLayout` which adds a suffix "_3d" to `layout_name` if `dim = 3`.
Fixes: exe-1901
Updated tests for `Plot3DGraph` and `ComputeLayout` to handle new layout names.

added suffix to layout name in ComputeLayout

---

.github/workflows/R-CMD-check.yaml
CHANGELOG.md
DESCRIPTION
R/graph_conversion.R
R/load_cell_graphs.R
R/write_pxl_file.R
tests/testthat/test-graph_conversion.R

The latest r-arrow version available is 17.0.0 and it is also available on conda-forge. There has been a number of updates that are not backwards compatible. 
For instance, upia and upib columns in the edgelist are now intepreted as dictionaries (used to be strings) which breaks a number of filtering steps required to load component graphs from the edgelist parquet file.
Fixes: exe-1816
Tested with the latest version of r-arrow. Should be compatible with older versions of r-arrow.

Updates for arrow 17 compatibility

---

.Rbuildignore
.gitignore
DEVELOPERS.md
Taskfile.yml
environment.yml
inst/dev/install-deps.R
inst/dev/style-staged.R
inst/dev/test-staged.R

This PR adds a number of tasks to simplify package development. Below is a list of the tasks included:
- `setup-env-bare` : Create a new environment with micromamba with base R installed
- `setup-env-pixelatorR` : Create a new environment with micromamba with pixelatorR and its dependencies installed
- `install-pixelatorR-with-pak` : Install pixelatorR and its dependencies to an existing micromamba environment using pak. This can be useful as an alternative option to facilitate install on arm architectures.
- `document` : Runs devtools document on the R package.
- `test-all` : Runs all tests using testthat.
- `test-examples` : Runs all examples using devtools::test()
- `test-staged-files` : Runs tests for staged test R scripts. This can be useful to set up pre-commit hooks.
- …

Exe 1941 pixelatorR tasks

---

CHANGELOG.md
DESCRIPTION
R/CellGraphAssay.R
R/differential_colocalization_analysis.R
R/differential_polarity_analysis.R
R/generics.R
R/graph_layout.R
R/graph_layout_visualization.R
R/load_data.R
R/utils.R
man/ComputeLayout.Rd
man/RunDCA.Rd
man/RunDPA.Rd

Currently, we have some hard coded checks to validate polarity and colocalization score tables. We can update these to be less stringent which will enable loading other spatial metrics s.a. join-count statistics and conditional probabilities. 
These checks are also used when merging and subsetting data, so we will need to update these methods as well. 
Moreover, we have set some restrictions on what metrics can be used as input for RunDPA / RunDCA. We should be less stringent here as well to enable using other metrics as input.
This PR includes the following changes:
- `ReadMPX_counts` and `ReadMPX_Seurat` now handles PXL files with new spatial metrics
- `subset` and `merge` methods for class `MPXAssay` now only requires a few columns in the spatial metrics tables. For polarity scores, …

updated: load functions, merge, subset and RunDPA/RunDCA

---

CHANGELOG.md
R/load_data.R
R/utils.R

This fixes issues arising from missing items in the .pxl files. There are cases where spatial scores are missing from the .pxl file since this is optional when running the `pixelator` pipeline. Here we make sure that the files can still be loaded, but with appropriate warnings that files are missing. 
**An example**
If we attempt to load a spatial score item from a file missing it: 
```
> ReadMPX_Seurat("a_sample_file.pxl", 
+                load_polarity_scores = FALSE,
+                load_colocalization_scores = TRUE)
Error in `FUN()`:
! Failed to extract colocalization.parquet from a_sample_file.pxl
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
The pxl file 'a_sample_file.pxl' is missing: 
colocalization.parquet
polarization.parquet 
```
However, if we …

fix: allow missing spatial scores

---

CHANGELOG.md
R/differential_colocalization_analysis.R
R/differential_polarity_analysis.R
R/generics.R
man/RunDCA.Rd
man/RunDPA.Rd

`RunDPA/RunDCA` supports parallel processing with the `pbapply` R package. When warnings are generated, which is not too uncommon for small population sizes, the processing slows down substantially or even halts completely. The problem appears to be related to the communication between threads.
Thousands of tests are typically run for each marker (DPA) or marker pair (DCA) across multiple comparisons. A few of these tests will likely fail in which case a warning is thrown and the test is simply skipped.  
This PR adds a fix for this issue by silencing warnings when parallelization is enabled. The behaviour is documented in the function docs for `RunDPA/RunDCA`.
Fixes: exe-2068
Please describe the tests that you ran to verify your changes. …

fix: silenced warnings in RunDPA/RunDCA

---

CHANGELOG.md
R/load_cell_graphs.R
R/load_data.R
tests/testthat/test-LoadCellGraphs.R

`LoadCellGraphs` should not accept duplicated cell ids. Currently, `LoadCellGraphs` can take duplicated cell ids, and therefore reports that more cells are loaded than actually are.
This PR adds a check to bail out if the cells ids are duplicated.
Fixes: EXE-2072
Added a test to make sure that `LoadCellGraphs`  bails out when duplicated cell ids are provided.

Exe 2072 dup cells error

---

CHANGELOG.md
R/graph_layout.R
man/ComputeLayout.Rd

`ComputeLayout.MPXAssay` supports parallel reading of cell graphs but this option was not enabled in `ComputeLayout.Seurat`. 
This PR contains a fix to enable this feature.
Fixes: EXE-1773
No additional tests added as the tests should not be parallelized.

chore: enabled parallelized ComputeLayout for Seurat objects

---

CHANGELOG.md
DESCRIPTION
R/aaa.R
R/inspect_pxl_file.R
R/load_cell_graphs.R
R/load_data.R
R/load_layouts.R
R/read_and_write_parquet.R
R/utils.R
R/write_pxl_file.R
man/ReadMPX_layouts.Rd

pixelatorR uses the zip R package to interact with zip files which apparently fails at unzipping files larger than 2GB. These are the files that triggered the bug:
PNA035_Sample1_S1.layout.dataset.pxl
PNA035_Sample2_S2.layout.dataset.pxl
PNA035_Sample5_S5.layout.dataset.pxl
This PR replaces `zip::unzip` with the base R alternative `utils::unzip`. The `zip` package has been moved to Suggests. 
Fixes: exe-2088
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce it when relevant.

Switched to base R unzip

---

CHANGELOG.md
R/molecule_rank_plot.R

This changes the class assertion of MoleculeRankPlot to numeric _or_ integer instead of integer. The affected column(s) were numeric class by default, which would lead to errors in the class assertion. 
Test suite has been run.

MoleculeRankPlot assertion numeric

---

R/read_edgelist.R
R/types_check.R
R/utils.R
man/CellGraphAssay5-methods.Rd
tests/testthat/test-ReadMPX_edgelist.R

- `ReadMPX_arrow_edgelist` doesn't correctly handle custom `edge_list_file`. This is a minor bug since the option is rarely used.
- `assert_file_ext` correctly throws an error when the wrong file extension is used, but the error message is misleading
This PR contains fixes for both issues and some small typo fixes.
Fixes: EXE-2108
Added tests for `ReadMPX_arrow_edgelist` to check that option `edge_list_file` is handled correctly.

Minor bug fixes

---

.github/workflows/test-coverage.yaml
.lintr
CHANGELOG.md
R/colocalization_heatmap.R
tests/testthat/test-RunDCA.R

This is a small fix on ColocalizationHeatmap that guarantees that the x and y axis has the same order when `symmetrise = TRUE` and `type = "dots"`. In some cases, the x and y axis would have different order. 
Tests were run, and a new one was added to check this bug.

fix: x and y axis guaranteed same order

---

CHANGELOG.md
DESCRIPTION
R/load_data.R

`zip::unzip` can fail with large PXL files and using the `utils::unzip` version is a safer option.
Fixes: exe-2120

swapped zip::unzip with utils::unzip

---

CHANGELOG.md
R/aaa.R
R/density_scatter_plot.R
R/types_check.R
man/type_check_helpers.Rd
tests/testthat/test-DensityScatterPlot.R

This fixes a bug in `DensityScatterPlot` where the default of `gate_type` would throw an error, as we didn't convert the default `gate_type = c("rectangle", "quadrant")` to a single value. I also added validation for the `colors` argument and took the opportunity to add an assert function `assert_valid_color` to check if all values in a vector are valid color hex codes or names.
Added tests and modified old ones to test for this bug.

Density scatter gate bug

---

CHANGELOG.md
R/density_scatter_plot.R

The x- and y-axis titles are currently marker1 and marker2 wheras they should be whatever string is passed with marker1 and marker1. This PR contains a fix for this bug.
Fixes: EXE-2151

fix: DensityScatterPlot not showing marker names

---

CHANGELOG.md
R/CellGraphAssay.R
R/PNAAssay.R
R/differential_abundance_analysis.R
man/RunDAA.Rd
tests/testthat/test-MPXAssay-methods.R
tests/testthat/test-PNAAssay-methods.R

The `subset` methods for `PNAAssay` and `CellGraphAssay` do not correctly handle cases when all component IDs for a specific sample are removed. For instance, let's say you have a Seurat object with two associated PXL files and we use `subset` to remove all components for PXL file 2, a row is still kept in the `fs_map` slot for PXL file two but with an empty `id_map`. This PR contains a fix to make sure that such rows are dropped from the `fs_map` table.
Fixes: exe-2153
Added tests for `subset.MPXAssay` and `subset.PNAAssay` to test the fix.

fix: bug in subset method

---

R/duckdb_methods.R
man/PixelDB.Rd

A recent update to the [R6 package](https://r6.r-lib.org/news/index.html) advices to make the finalize method private. This is currently ok, but will become deprecated eventually.
Fixes: EXE-2156

fix: moved finalize method

---

R/duckdb_methods.R

This PR hard codes the name of the table in the database when lazy loading an edgelist from a PXL file.
Fixes: EXE-2159

defined table name for lazy table

---

CHANGELOG.md
R/PNAAssay.R
R/aaa.R
R/objects.R
man/ProximityScores.Rd
tests/testthat/test-ProximityScores.R

This PR introduces a new feature in `ProximityScores` to add two new columns: `p1` and `p2`, which correspond to the fraction of total UMIs in the corresponding component. These values can be used for downstream filtering. The option can be invoked by setting `ProximityScores(..., add_marker_proportions = TRUE)`.
Fixes: PNA-835
Added tests to `test-ProximityScores.R`.

Added option to ProximityScores

---

CHANGELOG.md
R/colocalization_heatmap.R
R/density_scatter_plot.R
tests/testthat/test-ColocalizationHeatmap.R
tests/testthat/test-DensityScatterPlot.R

`DensityScatterPlot` had a bug that caused % cells labels to be duplicated across facets, when labels should indicate percentage per each facet independently. I also did some refactoring, simplifying to make the code a bit easier to maintain.
Fixes: PNA-911
Manual testing to see that plots produce expected results.

fix: DensityScatterPlot label bug

---

CHANGELOG.md
R/density_scatter_plot.R
man/DensityScatterPlot.Rd
pixelatorR.Rproj
tests/testthat/test-CellGraph-methods.R
tests/testthat/test-DensityScatterPlot.R

This PR restores a previous behavior of `DensityScatterPlot` to have the same range of the x and y axis. This can now be controlled using a new argument `equal_axis`; if set to `TRUE` (default) the x and y axes will range to the common min-max range of either axis. The `margin_density` argument is now `FALSE` by default, as it gives a cleaner look and avoids the warning message of incompatibility with `coord_fixed = TRUE`.
Manual testing.

fix: restored lost equal axes feature

---

CHANGELOG.md
R/aaa.R
R/doublet_detection.R
R/generics.R
man/PredictDoublets.Rd
man/patch_detection.Rd
pixelatorR.Rproj
tests/testthat/test-PredictDoublets.R

This  adds the `iter` argument for doublet detection, allowing `PredictDoublets` to run several iterations with the same parameters, increasing the robustness of results across runs. Setting `iter = 1` (default) is identical to previous behavior.
New tests have been added.

Doublet detection iteration

---

CHANGELOG.md
R/PNAAssay.R
R/duckdb_methods.R
R/lazy_load_tables.R
R/objects.R
man/Edgelists.Rd
tests/testthat/test-Edgelists.R
tests/testthat/test-PixelDB.R

This contains some fixes and features to Duckdb functions, ensuring that edgelists are actually lazy loaded, and adds a mode of `.lazy_load_table` to not union tables. This can be useful for join operations downstream. 
Added tests to control for that the original function is preserved.

Lazy read edgelists

---

R/types_check.R

This fixes a small assertion function error, so that the assertion actually gives an informative error message when a filename `x` is NULL, while `allow_null = FALSE`. 
Manual testing.

fix: assertion NULL error
